name: Application terraform

on:
  workflow_dispatch:
  repository_dispatch:
    types: [app-update]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  IAM_ROLE: ${{ secrets.IAM_ROLE }}
  IAM_ROLE_NAME: ${{ secrets.IAM_ROLE_NAME }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./apps/dev

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        id: aws-credentials
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          role-session-name: ${{ env.IAM_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}
          output-credentials: true

      - name: Add AWS profile
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.aws-credentials.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.aws-credentials.outputs.aws-secret-access-key }}
          AWS_SESSION_TOKEN: ${{ steps.aws-credentials.outputs.aws-session-token }}
        run: |
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} --profile dstolarek-upskill-devops
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} --profile dstolarek-upskill-devops
          aws configure set aws_session_token ${{ env.AWS_SESSION_TOKEN }} --profile dstolarek-upskill-devops

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
