name: Infrastructure terraform

on:
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  IAM_ROLE: ${{ secrets.IAM_ROLE }}
  IAM_ROLE_NAME: ${{ secrets.IAM_ROLE_NAME }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./infra/dev

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        id: aws-credentials
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          role-session-name: ${{ env.IAM_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.aws-credentials.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.aws-credentials.outputs.aws-secret-access-key }}
          AWS_SESSION_TOKEN: ${{ steps.aws-credentials.outputs.aws-session-token }}
        run: terraform init
