name: Infrastructure terraform

on:
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  IAM_ROLE: ${{ secrets.IAM_ROLE }}
  IAM_ROLE_NAME: ${{ secrets.IAM_ROLE_NAME }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          role-session-name: ${{ env.IAM_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log
        run: |
          pwd
          ls -la

      - name: Navigate to Infra terraform
        run: cd ./infra/dev

      - name: Init terraform
        run: terraform init
